def parseMassTable():
    massDict = {}
    massFile = open("monoisotopic mass table.txt","r")
    for line in massFile:
        line = line.strip("\n")
        massDict.update({line.split(" ")[0]:line.split(" ")[1]})
    return massDict

def calculateProteinMass(aaString,massDict):
    total = 0
    for i in aaString:
        total += float(massDict[i])
    return total

aa = 'NSTKLQIDFMKSTQIKVKSEWWDTIWDYAWCIQDYMKMSMDMVKILFFVGWVGPEESEPYPFRRKGTMSKDMINPHMRLVDAISAPTVDYLFALWYKDLERFSAYQMGCYPHAAINWCYYTAHHHVQKDFTWSKTTDCEEVDVVGYKHFDIMTDMKCLSHQFRDSIIEIERQAITVVTNGFNRANETTIKCADILCPNDPYHYQHCTCHVIIMWGFCLYPSDTFWTNGGAWWEQPADVTRCCGQADEVVSETVEDQTHHVWSFFYTEAMDCHQKWGSENYPQQKYEHLYPLQYSDLVELDSAWENWLRYMAWKCGHVKRMQTHREQEEHNMEDNVPREKMPLDRRKVQCIRWWEGLREDYCDNFVFHPCVQKWMDMIKKCSANIDIAGKPMSNVMGPLNSEAQAETHFARHLGQDRSMQTIAIAWPVQAQPMHWTMHGVWSTIYLPKHCDIHGQGWLQNKTPAIYQEDSSQRGSACGCITTVKGAMWSRHDMDWRKEAIDQTYTLILISYDQSRMINNVVTKRFETCPAQINHVSMVSMRHPKAFTHRTYDCPEMWGFKPNPSGPKAMIFWDSFQLGPDMVFNAWVEHFRFRKPQHTMKCAEYVSGEASHMLKMADKEFKWLVSLDAEVPPDMYDVGVYKPIKEAHVEICNLDQLRQPVEEINWTYYDFAYITFRMWQAPPITCQNYKEQRKSCAVQAHMSFKKMLMEAIIQDQMGMIGGPILITASHPWSEGAQKRWKEPSYYENFHCARTFIWIGFQSNTFRWIEYQIIYSSEPMVGIWKDWQNEFPKPWHLHQGAQRCMPRLFVPMVRKCCMQGAHTDSQYRNVYEHCQTNFCTCDPKCSVCQSTCTGGFGYLTGRDGFQYMAMASAIWRAVCSWHVRNIAMIIIHSESVLLHRHGWNQQPEMFAMEWLPAVMQTGDQTPAKTWRWWKFEKNFFHEKVWWNATELCHIEVDSFTCHEQLFHNMPCCPDNYGSFKEIVGVGCFSAEAWCWCSSNHAC'
proteinMassDict = parseMassTable()
print(calculateProteinMass(aa,proteinMassDict))