def countNucleotide(dnaString,compareItem):
     occurance = ""
     occurance = occurance + str(dnaString.count(compareItem)) + " "
     #trimming the last space at the end.    
     return occurance   
dnaString = "GACCATGAAAGCAGCTTGGTCGTAGGGCAAAGGGCAAAGAATCAAAACCCCCGGCGTGTAAGTTCTGTCTTGAAACGTCGCGAGTAGGTAAAGTAGGATGGAATGCTTGTATTGAACTTATAGTGCGCTACAGAGCTCCGCGTTATGAAATAGTGAGTGCGTCGCAGTCGTCACTGTCCCGATTCTATGGAGACCTAGTTCCACCCTACGGTGAAGATACCCAAACTGTAGCACCGTGCTTCGATCCGTGCTCGCATGTCATTATCATCCGTTAAGCGTAACTCGCCCCGTTCCACGAGCGTACTGAACTTTCACATACAGGCCCCGTACATATCACAGGACTGTTTAATTGACCAACCGGATCCTAGAAGAAATCTTGATCAAAAGATGTGGCCTAGGCTCGTTGGGGACTTCAGCCTGAATTTGATGTGAAACGAGCCAATACTATCGGAGCAACCTCCAATACCTGTAAACCACACACTAATAAGAAGGGTTAGATAAGGTAGATCTTCTTTTCAGCCACGGGAAGCGTGCCGGGACCTAGGTGCGTACCCTATTCGCCTATCGCACAGTGGATGACCTAGAAATGGCATACGGCCGATCGCTTGTATCATGTAACGTGATATCGTGTTCGCAGGAATGTTGGCGTAATCGCACTACAATCGTCCTCGACGGCGAGATCTAGGGCCTGGTAAGTCGTTCTTAGCGCGTGTCAGTGAAATTCAGACGTCACATCGGGTTGCTCTAAAAATAACAAGGCGATTACAAACGACCACCCGGGTAGCAAGGATGCGCCGAACTATTGGGTTGGACA"
print(countNucleotide(dnaString,'A') + ' ' + countNucleotide(dnaString,'C') + ' ' + countNucleotide(dnaString,'G') + ' ' + countNucleotide(dnaString,'T'))