def findMotifInDNA(dnaSeq,motif):
    temp = ''
    for i in range(0,len(dnaSeq)-1):
        compItem = dnaSeq[i:(len(motif)+i)]
        if(motif == dnaSeq[i:(len(motif)+i)]):
            #array indexes start from 0 that's why it has to be str(i+1) just for visual purposes.
            temp = temp + ' ' + str(i+1)
    print(temp)

dnaSequence = "ATAGCACTAATAGCACATAGCACAATAGCACCTTATGTCGGATAGCACGAGGATAGCACATAGCACTATAGCACTATAGCACGAGATAGCACGGATAGCACTGAGAGCATAGCACTGATAGCACTCCAATAGCACATAGCACTACATAGCACATAGCACTAATAGCACATAGCACATAGCACATTACGAATAGCACATAGCACATAGCACCGTATAGCACATAGCACAATAGCACATAGCACCATAGCACACTAATAGCACTATAGCACGGCATAGCACCATAGCACGAGTAAATAGCACGTTGATAGCACACGATAGCACCGGGGATAGCACAGACGACATAGCACATAGCACTATAGCACATGATAGCACCCAACAATAGCACATAGCACATAGCACCGCGGTCAAGACATAAAGGTATAGCACATAGCACCATAGCACTAAGGATAGCACCAAAGCATAGCACTCATAGCACGATAGCACGTCCATAGCACGTATAGCACTATAGCACATAGCACGTTCATAGCACTATAGCACGCGCGTATAGCACCAGGGTTACCTATTAGGCTACATAGCACACAATAGCACTATAGCACTGCCCCACGTTATAGCACATAGCACGATAGCACGTATAGCACTTGTCTATAGCACACGAATTATAGCACGATAGCACAGCCCCATCTGAGAAATAGCACCATAGCACCACTGAGTATAGCACTAGTTATAGCACCCAGTAAATGATAGCACAATAGCACATAGCACCCCATAGCACGGGGATAGCACTATAGCACAATAGCACGAATAGCACGATATCAATAGCACACATAGCACGATAGCAC"
motive = "ATAGCACAT"
findMotifInDNA(dnaSequence,motive)

