def get_mRNA_combinationCount(proteinSeq,codonDict):
    #starts with 3 because there are 3 different stop codons.
    combination = 3;
    for i in proteinSeq:
        #converting dict. values into a list so we can use .count()      
        combination = combination * list(codonDict.values()).count(i)
    print(combination%1000000)

def getCodonDict():
    codonDict = {}
    codonsFile = open("codon table.txt","r")
    for line in codonsFile:
        line = line.strip("\n")
        codonDict.update({line.split(" ")[0]:line.split(" ")[1]})
    return codonDict

proteinSequence = "MFMDFTRDREDHPCHPFNGVREWCSNTHHMIPAKGEHMAVHQNAITHDYCWQNGFFVWYLCWWDIIGNLGPKLATEPWQDIVVGVDPHVRFFTMYMMLQFREACQLLKHAWNRLWFDTFANTSNQTQMFHQQYANGEHSHDYQFGNPDTWEVDMFNVKGADTQCAPHNRHCELGTAREDDKNCHEVQWPDLMCLRFKRKINSRHPRMTCQLPVVFLIVWTMNSFCRMFVVAFSIICHYMFQTDWPSDGQYKDVVQFWIECFKDLWILSGNFYIQQGTQQRTVETQPCYGPCMEGTYYWPREKFFNPLEAMRMYFIHDQSICMRGHTDEFALDVNNHVYKMYWLVPQIDICMMIQQPHESMAFMLEMDFVYLDAERVFRHPLIGTQGWDLHQDRPWFCSFHTEGGIWHYGQSDIVHWMPLPDYMFPHMYPTMARMDPKKVQIIRHGRVRWDFSFHANAANVNGFCPKLPATSNIEQVIVDIQANEYYWMHQDLWRPRQLSWHYYESVCFEIWIGDWVVWSQDRSRHHPRWYTGHVDVMCWEVQQLARTQRYDIDIQFKWAGAICCEPMKYFPFQLESHCNSVCMECQWKTMVTYSRKHSMVLFNEATHPAYFFFQEVMMCSKPLDEYKQCWVPLRMQCVNQGMECITCYIKQEVFMAHMIDDHLQFVFVCGAKNCIFHFRLSMVCRNMDQSTVCLVSLVCWIELLKLNAQGPFHYRPMRWTLHYNQVKSECHHRQGQRPCSEENNIMWPHHYHGYAEQFHFCHNMCQKFGSFCQKSRITAMLNHEKLDNERAASRFYIFIKLTGPIRWHFADEIATCVKYGYKYDGRISFHVNILCNQACTMSYNYSEGTGSNKRWNPQQVHDMYSDGTAWECFIVWFASWRECINHPVLYQFMERKHAHIMCTTSGEMAFIPQVRDTPVMCEHHNHGCAVGILYTACPKHNTFHKENDWGCPIEWFHSFRLATWHGNGCCIIEECNHDEDMFTEFKGCDLVSHIQVCEMQ"
get_mRNA_combinationCount(proteinSequence,getCodonDict())
